In [1]:
import os
import glob
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

# univariate cnn lstm example
from numpy import array
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers import TimeDistributed
from keras.layers.convolutional import Conv1D
from keras.layers.convolutional import MaxPooling1D

In [2]:
# split a univariate sequence into samples
def split_sequence(sequence, n_steps):
    X, y = list(), list()
    for i in range(len(sequence)):
        # find the end of this pattern
        end_ix = i + n_steps
        # check if we are beyond the sequence
        if end_ix > len(sequence)-1:
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return array(X), array(y)

In [27]:
# define input sequence
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# choose a number of time steps
n_steps = 4
# split into samples
X, y = split_sequence(raw_seq, n_steps)

In [28]:
print(X[0])
print("X shape: {}".format(X.shape))
print(y[0])
print("y shape: {}".format(y.shape))

[10 20 30 40]
X shape: (5, 4)
50
y shape: (5,)


In [29]:
t

[[[10]
  [20]]

 [[30]
  [40]]]
X shape: (5, 2, 2, 1)


In [24]:
# We define a 1D CNN Model for univariate time series forecasting as follows:
model = Sequential(name = "Univariate-Hybrid-CNN-LSTM")

# Number of neurons (nodes) are just about greater than the number of features.
# Rule of thumb is for number of neurons to be about 2/3 of the input    
num_neurons = 64

# CNN Layer
model = Sequential()
model.add(TimeDistributed(Conv1D(num_neurons, 1, activation= 'relu' ), input_shape=(None, n_steps, n_features)))
model.add(TimeDistributed(MaxPooling1D()))
model.add(TimeDistributed(Flatten()))
model.add(LSTM(50, activation= 'relu' ))
model.add(Dense(1))
model.compile(optimizer= 'adam' , loss= 'mse' )

In [25]:
model.fit(X, y, epochs=500, verbose=0)

In [26]:
# demonstrate prediction
x_input = array([60, 70, 80, 90])
x_input = x_input.reshape((1, n_seq, n_steps, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)

[[100.74967]]
